#!/usr/bin/env bash

modules=(cli interactive util)

# Load everything
if [[ $0 =~ -portable ]]; then
    echo "Testing bash-boost-portable"
    source latest/bash-boost-portable.sh
    export __bb_test_script="$PWD/latest/bash-boost-portable.sh"
else
    echo "Testing bash-boost"
    source latest/bash-boost.sh
    export __bb_test_script="$PWD/latest/bash-boost.sh"
    bb_load "${modules[@]}"
fi

# Make sure bb_expect works
(
    bb_expect "foo" "bar" &>/dev/null;
) && bb_fatal "bb_expect not working"
(
    bb_expect "foo" "foo" &>/dev/null;
) || bb_fatal "bb_expect not working"

for module in "${modules[@]}"; do
    tester="src/$module/_test.sh"
    [[ -r "$tester" ]] || bb_fatal "could not read $tester"
    source "$tester" || exit 1
done

bb_cleanup

(
    set -o posix; set | egrep "^(BB|__bb)_" 2>/dev/null
) && { echo "error: left behind variable(s)"; exit 1; }

(
    declare -F | egrep "^declare -f _?bb_" 2>/dev/null
) && { echo "error: left behind function(s)"; exit 1; }

echo "OK"
exit 0
