#!/bin/bash

# Load everything
if [[ $0 =~ -portable ]]; then
    echo "Testing bash-boost-portable"
    source bash-boost-*/bash-boost-portable.sh
else
    echo "Testing bash-boost"
    source bash-boost-*/bash-boost.sh
    bb_load "cli"
    bb_load "interactive"
    bb_load "util"
fi

bb_namespace "bb"

# Make sure bb_expect works
(
    bb_expect "foo" "bar" &>/dev/null;
) && bb_fatal "bb_expect not working"
(
    bb_expect "foo" "foo" &>/dev/null;
) || bb_fatal "bb_expect not working"

for module in cli interactive util; do
    tester="src/$module/_test.sh"
    [[ -r "$tester" ]] || bb_fatal "could not read $tester"
    source "$tester" || exit 1
done

exit 0

bb_startprof

bb_addopt "f:foo" "This is the foo arg (default: bar)" "bar"
bb_addflag "x:extra" "Use this to print an extra message"

bb_setprog "${BASH_SOURCE[0]##*/}"
bb_setpositional "NUMS" "List of integers"
bb_parseargs "$@"

foo="$(bb_cli_arg_getopt foo)"
echo "foo={$foo}"

if bb_checkopt "extra"; then
    echo "saw extra"
fi

nums=( $(bb_getpositionals) )
for pos in "${nums[@]}"; do
    echo "positional arg: $pos"
    bb_isint "$pos" || bb_fatal "not an int: $pos"
done

sum="$(bb_util_math_sum "${nums[@]}")"
min="$(bb_util_math_min "${nums[@]}")"
max="$(bb_util_math_max "${nums[@]}")"

echo "sum=$sum min=$min max=$max"

bb_kwparse "one=1" "two=2" || bb_error "kwargs failed to parse"
one=$(bb_kwget "one")
two=$(bb_kwget "two")

bb_expect "$one" "1" "kwargs consistency" 5
bb_expect "$two" "2"

bb_stopprof
