name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@main
      - name: Make source
        run:  make
  shellcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: shellcheck ./latest/bash-boost.sh ./latest/*/*.sh
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        container: ['bash:4.0', 'bash:4.4', 'latest']
    container: ${{ matrix.container }}
    steps:
        - run: make test
