name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['bash:4.0', 'bash:4.4', 'latest']
    container: ${{ matrix.container }}
    steps:
      - name: Install dependencies
        run: apk add --no-cache --virtual .build-deps make m4 coreutils
      - name: Fetch source
        uses: actions/checkout@main
      - name: Run tests
        run: make test
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@main
      - name: Make source
        run: make only
      - name: Run shellcheck
        run: shellcheck ./latest/bash-boost.sh ./latest/*/*.sh
