name: Run tests
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@main
      - name: Run shellcheck
        run: shellcheck ./latest/bash-boost.sh ./latest/*/*.sh
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['bash:4.0', 'bash:4.4', 'latest']
    container: ${{ matrix.container }}
    steps:
      - name: Fetch source
        uses: actions/checkout@main
      - name: Run tests
        run: make tests

